version: '3'
services:
  jekyll:
      image: jekyll/jekyll:pages
      container_name: xgopher-go-database-sql-tutorial
      command: jekyll serve --watch
      ports:
          - 3998:4000
      volumes:
          - ~/app/github.com/xgopher/go-database-sql-tutorial:/srv/jekyll/